config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :storages do
    resources :products
  end
  resources :product_types
  get 'search/:storage_id' => 'search#index', as: 'search'
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :storage
  belongs_to :product_type

  validates :product_name, presence: true, length: { minimum: 3 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :product_type_id, presence: true
  validate :expiration_date_cannot_be_in_the_past

    def expiration_date_cannot_be_in_the_past
      if expiration_date.present? && expiration_date < Date.today
        errors.add(:expiration_date, "can't be in the past")
      end
    end

  scope :expires_soon, -> do
    where('expiration_date =?', Date.today+3)
  end


  scope :in_stock, -> do
    where(
      'quantity > 1'
    ).order(id: :desc)
  end

  scope :running_low, -> do
    where(
      'quantity = ?', 1
    ).order(id: :desc)
  end

  scope :out_of_stock, -> do
    where(
     'quantity = ?', 0
    ).order(id: :desc)
  end

  scope :consumable, lambda { where('expiration_date > ?', Date.today) }

  scope :expires_today, lambda { where('expiration_date = ?', Date.today) }
  private

  def self.search(search)
    where("product_name LIKE ? OR expiration_date LIKE ? OR quantity LIKE ?",
          "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  def low_stock_info
    if @product.quantity.zero?
      shopping_list = []
      shopping_list << @product
    else
      notification_list = []
      notification_list << @product.product_name
    end
  end

  def expires_soon
    if @product.expires_soon
      eat_quickly = []
      eat_quickly << @product
    end
  end
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products
  validates :product_type, presence: true
  validates :unit, presence: true
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :user
  has_many :products
  validates :storage_name, presence: true

  scope :fridge, -> { where(storage_name: 'Fridge') }
  scope :refrigerator, -> { where(storage_name: 'Refrigerator') }
  scope :pantry, -> { where(storage_name: 'Pantry') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  after_create :add_default_storage_types_after_user_created
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :storages, dependent: :destroy
  has_many :products, through: :storages, dependent: :destroy

  private

 def add_default_storage_types_after_user_created
   Storage.create(storage_name: 'Fridge', user_id: self.id)
   Storage.create(storage_name: 'Refrigerator', user_id: self.id)
   Storage.create(storage_name: 'Pantry', user_id: self.id)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @storages = current_user.storages
  end

  def new
    @storage  = current_user.storages.new
  end

  def create
    @storage = current_user.storage.new(storage_params)
      if @storage.save
        flash[:notice] = 'You have created a new storage'
        redirect_to storage_path
      else
        flash[:error] = 'There were some problems with saving your storage'
        render :new
      end
  end

  def show

  end

  def destroy
    @storage.destroy
    flash[:notice] = "Storage @storage.storage_name has been deleted."
    redirect_to storage_path
  end

  private

  def storage_params
    params.require(:storage).permit(:storage_name)
  end

  def set_storage
    @storage = current_user.storage.find(params[:id])
  end
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:edit, :update, :destroy]

  def index
    # czy product_type?
    @product_types = ProductType.all
  end

  def show

  end

  def new
    @product_type = ProductType.new
  end

  def create
    @product_type = ProductType.new(product_type_params)
      if @product_type.save
        flash[:notice] = 'Product type created.'
       # session[:return_to] = request.referer
        # redirect_to product_types_path
       # czy redirect_to :back?????

      #  jeśli taki typ z jednostka istnieje nie twozr nowej!
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @product_type.update(product_type_params)
      flash[:notice] = 'Product type updated.'
      redirect_to product_types_path
    else
      render :edit
    end
  end


  def destroy
    if @product.product_type.empty?
      @product_type.destroy
      flash[:notice] = "Product type has been deleted."
    else
      flash[:notice] = "Product type assigned to product cannot be deleted"
    end
    redirect_to product_types_path
  end


  private
    def product_type_params
      params.require(:product_type).permit(:product_type, :unit)
    end

    def set_product_type
      @product_type = ProductType.find(params[:id])
      # @product_type = ProductsType.find(params[:product_type_id])
    end
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_storage, only: [:edit, :update, :destroy]

  def index
    @storages = current_user.storages
    @fridge = current_user.storage.where(storage_name: 'Fridge')
    @refrigerator = current_user.storage.where(storage_name: 'Refrigerator')
    @pantry = current_user.storage.where(storage_name: 'Pantry')
  end

  def new
    @storage  = current_user.storages.new
  end

  def create
    @storage = current_user.storages.new(storage_params)
      if @storage.save
        flash[:notice] = 'You have created a new storage'
        redirect_to root_path
      else
        flash[:error] = 'There were some problems with saving your storage'
        render :new
      end
  end

  def edit
  end

  def show
  end

  def destroy
    @storage.destroy
    flash[:notice] = "Storage #{@storage.storage_name} has been deleted."
    redirect_to root_path
  end

  def update
    if @storage.update(storage_params)
      redirect_to root_path, notice: 'Storage was successfully updated.'
    else
      render :edit
    end
  end

  protected
  def set_storage
    @storage = current_user.storages.find(params[:id])
  end

  private

  def storage_params
    params.require(:storage).permit(:storage_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        .brand-label= link_to image_tag('logo_stockup.png'), root_path, id: 'logo'
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to 'Account', edit_user_registration_path, class: 'btn btn-default'
          %li= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-default'
        - else
          %li= link_to 'Sign In', new_user_session_path, class: 'btn btn-default'
          %li= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    / Bootstrap CSS
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css", :integrity => "sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M", :rel => "stylesheet"}/

  %body
    = render 'layouts/header'

    - if notice
      #notice-wrapper
        %p#notice= notice
    - elsif alert
      #notice-wrapper
        %p#alert= alert

    .container
      = yield

app/views/product_types/_form.html.haml
= simple_form_for((@product_type)) do |f|
  - if @product_type.errors.any?
    #error_explanation
      %h3
        = pluralize(@product_type.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product_type.errors.full_messages.each do |message|
          %li= message
  %br/
  .field
    = f.input :product_type
    = f.input :unit

  .button
    = f.button :submit

app/views/product_types/edit.html.haml
= flash[:error] if flash[:error]
%h3 Edit product type
= render 'form', locals: { product_type: @type }

app/views/product_types/index.html.haml
%p#notice= notice
%h3 Product Types
%table
  %thead
    %tr
      %th Product Type
      %th Unit
      %th{:colspan => "5"}
  %tbody
    - @product_type.each do |product_type|
      %tr
        %td= product_type.product_type
        %td= product_type.unit
        %td= link_to 'Edit',  edit_product_type_path(product_type)
        %td= link_to 'Delete', product_type_path(product_type), method: :delete, data: { confirm: 'Are you sure you want to delete?' }
%br/
= link_to 'Add new product type', new_product_type_path

app/views/product_types/new.html.haml
%h3 New Product Type
= render 'form', product_type: @product_type
= link_to 'Back', new_product_type_path